/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Wechat;

import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.SwingUtilities;

public class Clients extends javax.swing.JFrame {
    
    private Socket s;
    private DataInputStream dis;
    private DataOutputStream dos;
    private String clientName = "Client";
    private static final Logger logger = Logger.getLogger(Clients.class.getName());
    
    public Clients() {
        initComponents();
        connectToServer();
    }

    private void connectToServer() {
        new Thread(() -> {
            try {
                s = new Socket("localhost", 5050);      //Connects to the server at localhost:5050
                dis = new DataInputStream(s.getInputStream());
                dos = new DataOutputStream(s.getOutputStream());
                
                // Get assigned name from server
                String nameMsg = dis.readUTF();
                if (nameMsg.startsWith("YOUR_NAME:")) {         //Server sends a message like YOUR_NAME:Client3
                    clientName = nameMsg.substring(10);         //Client extracts the name 
                    appendMessage("Joined as: " + clientName);  //Displays the assigned name in the chat
                }
                
                while (true) {
                    String msg = dis.readUTF();
                    // Only show messages not from this client
                    if (!msg.startsWith(clientName + ":")) {
                        appendMessage(msg);
                    }
                }
            } catch (SocketException se) {
                appendMessage("Disconnected from server: " + se.getMessage());
                //Error for server connection
            } catch (IOException e) {
                appendMessage("Connection error: " + e.getMessage());
                //Error for general connection problems
            } finally {
                closeResources();
            }
        }).start();
    }
    private void closeResources() {
        try {
            if (dis != null) dis.close();       //Closing this stops receiving message 
            if (dos != null) dos.close();       //Closing this stops message transmission
            if (s != null) s.close();           //Closing this terminates the connection completely
        } catch (IOException ex) {
            logger.log(Level.SEVERE, "Error closing resources", ex);
        }
    }
    

    // ... [keep all the existing GUI code] ...
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        TextField = new javax.swing.JTextField();
        Send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Client");

        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Send, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Send, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(TextField))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        // TODO add your handling code here:
        try {
            String msg = TextField.getText();
            if (dos != null) {
                dos.writeUTF(msg);
                SwingUtilities.invokeLater(() -> {
    SwingUtilities.invokeLater(() -> {
    TextArea.append(msg + "\n");
    TextArea.setCaretPosition(TextArea.getDocument().getLength());
});
    TextArea.setCaretPosition(TextArea.getDocument().getLength());
});
                TextField.setText("");
            }
        } catch (IOException e) {
            logger.log(Level.SEVERE, "Error sending message", e);
            TextArea.append("Failed to send message\n");
        }
    }//GEN-LAST:event_SendActionPerformed
     private void appendMessage(String msg) {
    SwingUtilities.invokeLater(() -> {
        TextArea.append(msg);
        if (!msg.endsWith("\n")) {
            TextArea.append("\n");
        }
        TextArea.setCaretPosition(TextArea.getDocument().getLength());
    });
}


     public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //Loops through all available Swing themes
                if ("Nimbus".equals(info.getName())) {
                    //Looks specifically for the "Nimbus"
                    //This makes the application look more modern than default Java UI
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //If found, activates it 
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            //Its for security restriction
            logger.log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Clients().setVisible(true);    
            //Creates an instance of your client application
            //Makes the window visible
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Send;
    private static javax.swing.JTextArea TextArea;
    private javax.swing.JTextField TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
